name: DetetiveMC
version: '${project.version}'
main: me.saulooliveira.detetivemc.DetetiveMC
api-version: 1.17
authors: [ SauloOliveira ]
description: Plugin criado para simular minigame detetive no Minecraft
commands:
  detetive:
    description: Comandos relacionados ao minigame Detetive
    usage: /<command> <arg>
    aliases:
      - dt
      - dtt
  reputacao:
    description: Comandos para gerenciar Reputacao
    usage: /<command> <arg>
    aliases:
      - rep
      - rp

